Repository chandan24042001s/Zummit, pull requests merged in 2024-06, with the labels that each got.

#76 fixing the bug admin route and filing the data on apis and testing
  backend/routes/adminRoute.js
Labels: peer review

#77 Admin : resolve admin login bug
  backend/controllers/Admin/adminController/register_Login.js
  backend/models/Admin/AdminRegisterLogin/adminModel.js
  frontend/src/components/Admin/Therapist/Therapist.js
Labels: Lead review

#78 Admin : integrated api in admin client for Resources & Reviews
  backend/models/Admin/AdminRegisterLogin/adminModel.js
  backend/routes/adminRoute.js
  frontend/src/components/Admin/Appointment/Appointment.js
  frontend/src/components/Admin/Client/Client.js
  frontend/src/components/Admin/Resources/Resources.js
  frontend/src/components/Admin/Reviews/Reviews.js
  frontend/src/components/Admin/Therapist/Therapist.js
Labels: Lead review

#79 fixing bug in Model-adminModel
  backend/controllers/Admin/adminController/register_Login.js
  backend/models/Admin/AdminRegisterLogin/adminModel.js
Labels: Lead review

#81 Admin : integrated api in Transaction
  backend/models/Admin/AdminDashboard/adminSecurity.js
  backend/routes/adminRoute.js
  frontend/src/components/Admin/Transactions/Transactions.js
Labels: peer review

#82 fixing Admin security issue
  backend/controllers/Admin/addedReviews.js
  backend/controllers/Admin/adminController/register_Login.js
  backend/controllers/Admin/adminDashboardController.js
  backend/controllers/Admin/appointmentsList.js
  backend/controllers/Admin/clientList.js
  backend/controllers/Admin/groupDetails.js
  backend/controllers/Admin/profile.js
  backend/controllers/Admin/resourcesList.js
  backend/controllers/Admin/reviews.js
  backend/controllers/Admin/therapistsDetails.js
  backend/controllers/Admin/transactions.js
Labels: peer review

#83 fixing Admin resourcesList , reviews , transactions & register_Login …
  backend/controllers/Admin/resourcesList.js
  backend/controllers/Admin/reviews.js
  backend/controllers/Admin/transactions.js
Labels: Lead review

#85 create post api for admindashboard
  backend/controllers/Admin/adminDashboardController.js
  backend/routes/adminRoute.js
Labels: peer review

#86 create authorization functionality
  backend/controllers/Admin/adminController/register_Login.js
  backend/controllers/Admin/therapistsDetails.js
  backend/middleware/authorizationMiddleware.js
  backend/routes/adminRoute.js
Labels: Lead review

#84 Backend For Appointment
  backend/config/database.js
  backend/controllers/Booking/BookingSlotsController.js
  backend/index.js
  backend/middleware/authMiddleware.js
  backend/middleware/errorMiddleware.js
  backend/models/Appointment/AppointmentModel.js
  backend/models/User/userModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/bookingRoute.js
  frontend/src/components/Footer.js
Labels: Lead review

#87 Add package-lock.json
  backend/package-lock.json
Labels: Lead review

#88 PR for changes in routing, API, and functionality for booking
  frontend/src/App.js
  frontend/src/components/BookTherapistPage.js
  frontend/src/components/FAQ.js
  frontend/src/components/Meet.js
  frontend/src/components/Navbar.js
  frontend/src/components/TherapistDetailsPage.js
  frontend/src/components/Therapists.js
  frontend/src/utils/userSlice.js
Labels: Lead review

#89 Admin : Create route fot therapist register and fix minor bugs
  backend/controllers/Admin/therapistCredentials/createCredentials.js
  backend/middleware/authorizationMiddleware.js
  backend/models/Therapist/therapistModel.js
  backend/routes/adminRoute.js
Labels: peer review

#90 Create routes for loginTherapist and logoutTherapist
  backend/index.js
  backend/routes/therapistRoute.js
Labels: Lead review

#92 PR to add Booking Controller
  backend/controllers/Booking/BookingSlotsController.js
  backend/controllers/Booking/bookingAppointment.js
  backend/controllers/Booking/patientDetails.js
  backend/controllers/Booking/therapistDetails.js
  backend/models/Appointment/AppointmentModel.js
  backend/routes/bookingRoute.js
Labels: peer review

#93 Therapist login frontend api integration done 🥵!
  frontend/src/App.js
  frontend/src/components/RegisterLogin.js
  frontend/src/components/TherapistHome.js
Labels: peer review

#94 group details frontend api integration done
  backend/routes/adminRoute.js
  frontend/src/components/Admin/Groups/Groups.js
Labels: peer review

#96 Remove unnecessary files
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: peer review

#98 Redux bug fix
  backend/controllers/User/userController.js
  frontend/src/components/Admin/Register_Loigin/Loader.js
  frontend/src/components/Admin/Register_Loigin/Login.js
  frontend/src/components/RegisterLogin.js
Labels: peer review

#101 Admin : Fixing bug in admin register api for cloudinary
  backend/controllers/Admin/adminController/register_Login.js
  backend/package-lock.json
  backend/package.json
Labels: Lead review

#102 Fixing bug and optimising the code in Admin - reviews and resourcesList and reviews
  backend/controllers/Admin/resourcesList.js
  backend/controllers/Admin/reviews.js
  backend/controllers/Admin/transactions.js
Labels: Lead review

#103 Admin Dashboard: Identified defects while comparing or testing the Figma Design and Live UI
  Testing/Figma Design.png
  Testing/Live UI.png
  testing_Documentation.json
Labels: Lead review

#104 Fixing bugs and optimizing the code in reviews In Admin section
  frontend/src/components/Admin/Appointment/Appointment.js
  frontend/src/components/Admin/Client/Client.js
  frontend/src/components/Admin/Dashboard/AdminDashboard.js
  frontend/src/components/Admin/Dashboard/Author.js
  frontend/src/components/Admin/Dashboard/Main_Dashboard.js
  frontend/src/components/Admin/Dashboard/Resources_Edit.js
  frontend/src/components/Admin/Groups/Groups.js
  frontend/src/components/Admin/Profile/Proflie.js
  frontend/src/components/Admin/Register_Loigin/Login.js
  frontend/src/components/Admin/Register_Loigin/SignUp.js
  frontend/src/components/Admin/Resources/Admin_Resources.js
  frontend/src/components/Admin/Resources/Resources.js
  frontend/src/components/Admin/Reviews/Reviews.js
  frontend/src/components/Admin/Therapist/AddTherapist.js
  frontend/src/components/Admin/Therapist/Admin_Therapists.js
  frontend/src/components/Admin/Therapist/Therapist.js
Labels: peer review

#105 Bug: booking click button solved
  frontend/src/components/TherapistDetailsPage.js
Labels: Lead review

#106 Changes in redux nomenclature
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BookTherapistPage.js
  frontend/src/components/FeedBackSection.js
  frontend/src/components/GroupTherapyDetail.js
  frontend/src/components/RegisterLogin.js
  frontend/src/components/TherapistDetailsPage.js
  frontend/src/utils/bookingSlice.js
  frontend/src/utils/store.js
  frontend/src/utils/userSlice.js
Labels: peer review

#107 Persisted store added to solve redux bug
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TherapistDetailsPage.js
  frontend/src/index.js
  frontend/src/utils/store.js
Labels: help wanted

#109 Implemented the searching algorithm .
  backend/controllers/Booking/therapistDetails.js
  backend/routes/bookingRoute.js
  frontend/src/components/Therapists.js
Labels: Lead review

#111 Appointment list controller
  backend/controllers/User/appointmentList.js
Labels: peer review

#112 created create route model & controller therapistAppointment
  backend/controllers/Therapist/therapistAppointmentsController.js
  backend/models/Therapist/therapistAppointmentsModel.js
  backend/routes/therapistRoute.js
Labels: Lead review

#113 [FE] : Admin login and Register
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Admin/Register_Loigin/Login-reg.js
  frontend/src/components/Admin/Register_Loigin/Login.js
  frontend/src/components/Admin/Register_Loigin/SignUp-reg.js
  frontend/src/components/Admin/Register_Loigin/SignUp.js
  frontend/src/components/images/Admin-login-bg.jpeg
Labels: Lead review

#115 Created Therapist Group Controller,Models and routes
  backend/controllers/Therapist/therapistGroupsController.js
  backend/models/Therapist/therapistGroupsModel.js
  backend/routes/therapistRoute.js
Labels: Lead review

#114 created model route and controller for group therapy and support group
  backend/controllers/User/groupTherapyController.js
  backend/controllers/User/supportgroupController.js
  backend/models/User/grouptherapymodel.js
  backend/models/User/supportgroupmodel.js
  backend/routes/userRoute.js
Labels: peer review

#117 Created API for upcoming Groups
  backend/controllers/User/upcomingGroups.js
  backend/controllers/User/userController.js
  backend/models/User/AppointmentModel.js
  backend/models/User/upcomingGroups.js
  backend/routes/userRoute.js
Labels: peer review

#119 Added calendar functionality in appointment booking page
  frontend/src/components/BookTherapistPage.js
Labels: Lead review

#118 Admin Clients: Identified Defects while comparing or testing both Admin Clients Figma design and Admin clients Live UI.
  Testing/Admin Appointments Figma Design.png
  Testing/Admin Appointments Live UI.png
  Testing/Admin Client Live UI.png
  Testing/Admin client Figma Design.png
  testing_Documentation.json
Labels: Lead review

#124 Therapist : Create api for therapist Observation
  backend/controllers/Therapist/therapistObservationController.js
  backend/models/Therapist/therapistObservationModel.js
  backend/routes/therapistRoute.js
Labels: peer review

#125 therapist transaction controller, model,routes
  backend/controllers/Therapist/therapistTransactionsController.js
  backend/models/Therapist/therapistTransactionsModel.js
  backend/routes/therapistRoute.js
Labels: peer review

#121 created Therapist model , improved the booking routes, updated the searching algo.
  backend/index.js
  backend/models/Therapist/therapistModel.js
  backend/routes/bookingRoute.js
  backend/routes/userRoute.js
  frontend/src/components/Therapists.js
  frontend/src/utils/fetchData.js
Labels: peer review

#122 Added Razorpay Integration Backend
  backend/config/razorpay.js
  backend/controllers/User/paymentController/orders.js
  backend/controllers/User/paymentController/paymentDetails.js
  backend/index.js
  backend/models/User/paymentModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/userRoute.js
Labels: peer review

#120 AppointmentList API Created
  backend/controllers/User/appointmentList.js
  backend/models/User/AppointmentModel.js
  backend/routes/userRoute.js
Labels: peer review

#126 therapist login and signup
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Admin/Register_Loigin/Loader.js
  frontend/src/components/Admin/Register_Loigin/Login.js
  frontend/src/components/Admin/Register_Loigin/SignUp.js
  frontend/src/components/Therapist/Dashboard/Dashboard.js
  frontend/src/components/Therapist/Dashboard/Therapist_Dashboard.js
Labels: peer review

#132 [FE] : Complete Therapist Details Module
  frontend/src/components/Therapist/Clients/Substance_Recovery.js
  frontend/src/components/Therapist/Profile/Proflie.js
  frontend/src/components/Therapist/Profile/Therapist_Profile.js
  frontend/src/components/Therapist/Responses/Responses.js
  frontend/src/components/Therapist/Responses/Therapist_Responses.js
  frontend/src/components/Therapist/Schedules/Schedules.js
  frontend/src/components/Therapist/Schedules/Therapist_Schedules.js
  frontend/src/components/Therapist/Transactions/Therapist_Transactions.js
  frontend/src/components/Therapist/Transactions/Transactions .js
Labels: peer review

#135 [FE] : Login Registered API endpoint changed to chandan Backend
  frontend/src/components/RegisterLogin.js
Labels: peer review

#138 Admin Review : Validated Admin Review Live UI and Admin Review Figma desing
  Testing/Admin Review Figma Design.png
  Testing/Admin Review Live UI.png
  testing_Documentation.json
Labels: Lead review

#139 Therapist : integrate Therapist Observation API to frontend
  frontend/src/components/Therapist/Observation/Observation.js
Labels: Lead review

#140 [FE] Therapist : integrate Therapist Appointments API to frontend
  frontend/src/components/Therapist/Appointment/Appointment.js
Labels: peer review

#144 Login Required PopUp, checkToken, verifyClient to give access of booking page
  backend/controllers/Booking/therapistDetails.js
  backend/controllers/User/userController.js
  backend/index.js
  backend/models/Therapist/therapistSchedule.js
  backend/routes/userRoute.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/BookTherapistPage.js
  frontend/src/components/IndividualThearapy.js
  frontend/src/components/PopUps/LoginReq_pop.js
  frontend/src/components/TherapistDetailsPage.js
  frontend/src/components/Therapists.js
  frontend/src/utils/checkToken.js
  frontend/src/utils/fetchData.js
  frontend/src/utils/verifyClient.js
Labels: peer review

#148 [FE] - TheripistAppointment fix the api
  frontend/src/components/Therapist/Appointment/Appointment.js
Labels: peer review

#149 Therapist observation
  .gitignore
  backend/.gitignore
  frontend/src/components/Therapist/Observation/Observation.js
Labels: Lead review

#150 Merge branch 'main' of https://github.com/kuldeepsaini2003s/Zummit
  frontend/src/components/RegisterLogin.js
  frontend/src/components/Therapist/Register_Loigin/Therapist_Login.js
  frontend/src/components/Therapist/Register_Loigin/Therapist_Signup.js
Labels: peer review

#151 [FE] : Hot Fix for Admin Login UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Admin/Register_Loigin/SignUp.js
  frontend/src/components/Navbar.js
Labels: peer review

#152 [FR] Hot Fix for Admin fixing LoginAdmin functionality and register API integration
  frontend/package-lock.json
  frontend/src/components/Admin/Register_Loigin/Login.js
  frontend/src/components/Admin/Register_Loigin/SignUp.js
Labels: Lead review

#155 [FE] : Shimmer Effect for Therapist Dashboard
  frontend/src/App.css
  frontend/src/components/Admin/Register_Loigin/SignUp.js
  frontend/src/components/RegisterLogin.js
  frontend/src/components/Therapist/Appointment/Appointment.js
  frontend/src/components/Therapist/Dashboard/Shimmer.js
  frontend/src/components/Therapist/Dashboard/Therapist_Dashboard.js
Labels: peer review
