Repository chandan24042001s/Zummit, pull requests merged in 2024-05, with the labels that each got.

#47 Booking slots part 1 - routing
  frontend/src/App.js
  frontend/src/components/BookingPage.js
  frontend/src/components/TherapistProfile.js
  frontend/src/components/Therapists.js
  frontend/src/components/therapistProfileCard.js
Labels: Lead review

#57 Create post api for profile & groupDetails and controllers
  backend/controllers/Admin/groupDetails.js
  backend/controllers/Admin/profile.js
  backend/routes/adminRoute.js
Labels: good first issue

#58 create post api for therapistsDetails and transactions
  backend/controllers/Admin/therapistsDetails.js
  backend/controllers/Admin/transactions.js
  backend/routes/adminRoute.js
  package-lock.json
Labels: peer review

#59 create post api for reviews and controller
  backend/controllers/Admin/reviews.js
Labels: peer review

#62 Create post api for adminRegister
  backend/controllers/Admin/reviews.js
  backend/routes/adminRoute.js
Labels: peer review

#63 Create post api for adminLogin
  backend/routes/adminRoute.js
Labels: peer review

#64 Create post api for createResource
  backend/routes/adminRoute.js
Labels: peer review

#65 Bug : email field mismatch
  backend/controllers/Admin/appointmentsList.js
Labels: peer review

#66 Bug : input field mismatch and minor bug fixing
  backend/config/database.js
  backend/controllers/Admin/clientList.js
  backend/controllers/Admin/reviews.js
  backend/controllers/Admin/therapistsDetails.js
  backend/controllers/Admin/transactions.js
  backend/routes/adminRoute.js
Labels: peer review

#69 fixing minor bugs in - client , Profiles, groupDetails , resoursesList
  backend/controllers/Admin/clientList.js
  backend/controllers/Admin/groupDetails.js
  backend/controllers/Admin/profile.js
  backend/controllers/Admin/resourcesList.js
Labels: Lead review

#70 fixing minor bugs in-addedReview,adminDashboard
  backend/controllers/Admin/addedReviews.js
  backend/controllers/Admin/adminDashboardController.js
Labels: Lead review

#71 Bug : fixing bug for Unauthorized user
  backend/controllers/Admin/reviews.js
  backend/controllers/Admin/therapistsDetails.js
  backend/controllers/Admin/transactions.js
Labels: peer review

#72 fixing bug for addedReviews , adminDashboardController , appointmentL…
  backend/controllers/Admin/addedReviews.js
  backend/controllers/Admin/adminDashboardController.js
  backend/controllers/Admin/appointmentsList.js
  backend/controllers/Admin/clientList.js
Labels: peer review

#73 fixing bug for groupDetails,profile,resourcesList
  backend/controllers/Admin/groupDetails.js
  backend/controllers/Admin/profile.js
  backend/controllers/Admin/resourcesList.js
Labels: Lead review

#74 Create update api for resourcesList
  backend/controllers/Admin/resourcesList.js
  backend/routes/adminRoute.js
Labels: Lead review

#75 Admin : integrated api in admin deshborad for Appointment & Therapist
  backend/controllers/Admin/appointmentsList.js
  backend/models/Admin/adminTherapist.Model.js
  backend/routes/adminRoute.js
  frontend/src/components/Admin/Appointment/Appointment.js
  frontend/src/components/Admin/Therapist/Therapist.js
Labels: Lead review
